# Generated by Django 3.0.3 on 2020-02-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='archive_file',
            new_name='file',
        ),
    ]
