# Generated by Django 3.0.3 on 2020-02-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20200224_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Observation date.')),
                ('temperature', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('barometricPressure', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('windSpeed', models.IntegerField()),
                ('windDirection', models.CharField(max_length=3)),
            ],
        ),
    ]
