# Generated by Django 3.0.3 on 2020-02-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='observations',
            field=models.ManyToManyField(blank=True, to='archive.Observation'),
        ),
    ]
