# Generated by Django 3.0.3 on 2020-02-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_archive_observations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='observations',
        ),
    ]
