# Generated by Django 3.0.3 on 2020-02-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('change_delete_task', 'Change or delete task'),)},
        ),
    ]
